name: vllm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pillow
  - pip:
    - gradio==5.6.0
    - requests
    - openai==1.54.0
    - pydantic==2.9.2
    - pddl==0.4.1
    - python-dotenv
    - mistralai
    - ngrok
    - transformers==4.51.3
    - vllm==0.8.5
