mode: explicit_state_action
succ_prompt: 'You are a smart assistant that answers concisely.

  You will be given a problem / question to solve.

  This is your problem statement:'
gen_action_prompt: "Now you must find the next action based on the current state of the world to reach the goal? Give your reasoning and then '[OUTPUT]' followed by the next action for solving the problem or '[FINISHED]' if you are done."
current_state_prompt: 'After applying the plan, this is the current state of the world:'
progress_prompt: "This is the plan so far:"
map_succ_prompt: "What is the state of the world after applying this action? Give your reasoning and then '[OUTPUT]' followed by a concise but complete description of the state of the world."
novelty: False
